spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rest_with_spring_boot_erudio?useTimezone=true&serverTimezone=UTC

    username: postgres

    password: root
  jpa:
    hibernate:
      ddl-auto: update

    show_sql: false
    open-in-view: false