spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rest_with_spring_boot_erudio?useTimezone=true&serverTimezone=UTC

    driver-class-name: org.postgresql.Driver

    username: postgres

    password: root

  flyway:
    enabled: true

    url: jdbc:postgresql://localhost:5432/rest_with_spring_boot_erudio?useTimezone=true&serverTimezone=UTC

    user: postgres

    password: root

    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: none

    show_sql: false
    open-in-view: false