CREATE TABLE p01_person
(
    p01_codigo_pessoa BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    p01_first_name    VARCHAR(255)                            NOT NULL,
    p01_last_name     VARCHAR(255)                            NOT NULL,
    p01_address       VARCHAR(255),
    p01_gender        VARCHAR(255),
    CONSTRAINT pk_p01_person PRIMARY KEY (p01_codigo_pessoa)
);
